import CtaBanner from "@/components/cta-banner";
import SiteFooter from "@/components/site-footer";
import SiteHeader from "@/components/site-header";
import type { Locale } from "@/lib/i18n";

const copy = {
  vi: {
    eyebrow: "VỀ KAT SOLUTIONS", title: <>Những chuyển đổi lớn<br />bắt đầu từ một bước nhỏ.</>, body: "KAT Solutions đồng hành cùng doanh nghiệp từ việc làm rõ một vấn đề cụ thể đến xây dựng hệ thống ERP, CRM, nền tảng Web và các giải pháp AI, Computer Vision có thể vận hành, đo lường và mở rộng.",
    storyEyebrow: "CÂU CHUYỆN KAT", storyTitle: <>Từ một bước nhỏ<br />đến giá trị bền vững.</>, storyBody: "Chúng tôi tin rằng một chuyển đổi lớn không bắt đầu bằng công nghệ phức tạp, mà bằng việc nhìn đúng một vấn đề và thực hiện bước đầu tiên. KAT Solutions làm việc sát với quy trình thực tế, kết nối dữ liệu rời rạc và từng bước biến ý tưởng thành sản phẩm hữu ích, đáng tin cậy và có thể phát triển lâu dài.",
    metrics: [["05", "Nhóm giải pháp"], ["01", "Đội ngũ đồng hành"], ["∞", "Khả năng mở rộng"]], ecosystem: "HỆ SINH THÁI GIẢI PHÁP", ecosystemTitle: "Ba nhóm giải pháp. Một mục tiêu.",
    capabilities: [["01 · BUSINESS SYSTEMS", "ERP và CRM giúp doanh nghiệp chuẩn hóa quy trình, kết nối dữ liệu và vận hành trên một nguồn thông tin thống nhất."], ["02 · DIGITAL PRODUCTS", "Website doanh nghiệp và nền tảng Web được thiết kế rõ ràng, hiệu quả và có thể mở rộng cùng hoạt động kinh doanh."], ["03 · INTELLIGENT SOLUTIONS", "AI, Automation và Computer Vision đưa dữ liệu và khả năng quan sát vào kiểm tra, giám sát và ra quyết định."]],
    principlesEyebrow: "CÁCH KAT TẠO RA GIÁ TRỊ", principlesTitle: <>Bắt đầu nhỏ.<br />Xây dựng đúng.</>, principles: [["01 · Bắt đầu từ vấn đề rõ nhất", "Chọn một bài toán đủ cụ thể để kiểm chứng giá trị bằng kết quả thực tế."], ["02 · Xây dựng cho vận hành thực tế", "Ưu tiên giải pháp dễ sử dụng, có thể đo lường, bảo trì và mở rộng."], ["03 · Đồng hành để đi xa hơn", "Cùng khách hàng cải tiến liên tục từ bước đầu tiên đến hệ thống hoàn chỉnh."]],
  },
  en: {
    eyebrow: "ABOUT KAT SOLUTIONS", title: <>Great transformations<br />start with one small step.</>, body: "KAT Solutions works with businesses to clarify a real challenge, then build ERP, CRM, Web platforms, AI, and Computer Vision solutions that can operate, be measured, and scale.",
    storyEyebrow: "THE KAT STORY", storyTitle: <>From one small step<br />to lasting value.</>, storyBody: "We believe meaningful transformation does not begin with complex technology. It starts by seeing the right problem and taking the first step. KAT Solutions works close to real operations, connects fragmented data, and turns ideas into useful, reliable products built to grow over time.",
    metrics: [["05", "Solution areas"], ["01", "Delivery team"], ["∞", "Room to scale"]], ecosystem: "SOLUTION ECOSYSTEM", ecosystemTitle: "Three solution groups. One goal.",
    capabilities: [["01 · BUSINESS SYSTEMS", "ERP and CRM help businesses standardize workflows, connect data, and run from one consistent source of information."], ["02 · DIGITAL PRODUCTS", "Corporate websites and Web platforms are designed to be clear, effective, and ready to grow with the business."], ["03 · INTELLIGENT SOLUTIONS", "AI, automation, and Computer Vision bring data and visibility into inspection, monitoring, and decision-making."]],
    principlesEyebrow: "HOW KAT CREATES VALUE", principlesTitle: <>Start small.<br />Build what matters.</>, principles: [["01 · Start with the clearest problem", "Choose a focused challenge where value can be proven through real results."], ["02 · Build for real operations", "Prioritize solutions that are easy to use, measurable, maintainable, and scalable."], ["03 · Stay with you as you grow", "Work with customers to improve continuously—from the first step to a complete operating system."]],
  },
} as const;

export const About = ({ locale = "vi" }: { locale?: Locale }) => {
  const text = copy[locale];
  return <main className="bg-[#070911]"><SiteHeader active="about" locale={locale} />
    <section className="bg-[#040406] text-[#d0d9fb] lg:h-[820px]"><div className="relative mx-auto grid min-h-[720px] max-w-[1608px] gap-12 overflow-hidden px-5 py-20 lg:block lg:h-[820px] lg:px-0 lg:py-0"><div className="lg:absolute lg:left-0 lg:top-[150px] lg:w-[1120px]"><p className="text-[14.4px] font-medium tracking-[.36px] text-[#fdda0d]">{text.eyebrow}</p><h1 className="display mt-8 text-4xl font-medium leading-tight sm:text-5xl lg:mt-7 lg:text-[48px] lg:leading-[60px]">{text.title}</h1><p className="mt-10 max-w-[980px] text-lg leading-8 lg:mt-[145px] lg:text-xl lg:leading-8">{text.body}</p><p className="mt-8 text-sm tracking-[.2em] lg:mt-[105px] lg:text-base lg:tracking-normal">ERP&nbsp;&nbsp;&nbsp; · &nbsp;&nbsp;&nbsp;CRM&nbsp;&nbsp;&nbsp; · &nbsp;&nbsp;&nbsp;WEB PLATFORM&nbsp;&nbsp;&nbsp; · &nbsp;&nbsp;&nbsp;AI&nbsp;&nbsp;&nbsp; · &nbsp;&nbsp;&nbsp;COMPUTER VISION</p></div><div className="relative mx-auto h-[410px] w-full max-w-[600px] lg:absolute lg:left-[1100px] lg:top-[120px] lg:h-[580px]"><img src="/images/about-network.svg" alt="KAT Solutions transformation network" className="absolute left-1/2 top-0 h-[360px] w-[404px] -translate-x-1/2 object-contain lg:left-5 lg:h-[500px] lg:w-[560px] lg:translate-x-0" /><span className="absolute left-1/2 top-1 text-[13px] font-medium lg:left-[270px]">WEB</span><span className="absolute left-8 top-[225px] text-[13px] font-medium lg:left-12 lg:top-[316px]">ERP</span><span className="absolute left-12 top-[86px] text-[13px] font-medium lg:left-[75px] lg:top-[112px]">CRM</span><span className="absolute right-12 top-[86px] text-[13px] font-medium lg:right-auto lg:left-[474px] lg:top-[112px]">AI</span><span className="absolute right-6 top-[225px] text-[13px] font-medium lg:right-auto lg:left-[490px] lg:top-[316px]">VISION</span><p className="absolute bottom-0 left-1/2 -translate-x-1/2 whitespace-nowrap text-[11px] tracking-[1.04px] lg:bottom-[42px] lg:left-[148px] lg:translate-x-0 lg:text-[13px]">START SMALL&nbsp;&nbsp;→&nbsp;&nbsp;BUILD CONNECTED</p></div></div></section>
    <section className="bg-white text-[#1a212d] lg:h-[920px]"><div className="relative mx-auto grid max-w-[1608px] gap-12 px-5 py-20 lg:block lg:h-[920px] lg:px-0 lg:py-0"><div className="lg:absolute lg:left-0 lg:top-[120px] lg:w-[780px]"><p className="text-[14.4px] font-medium tracking-[.36px] text-[#fdda0d]">{text.storyEyebrow}</p><h2 className="display mt-8 text-3xl font-semibold leading-tight lg:mt-7 lg:text-4xl lg:leading-[49.5px]">{text.storyTitle}</h2><p className="mt-10 text-lg leading-8 text-[#535a79] lg:mt-[105px] lg:text-xl lg:leading-8">{text.storyBody}</p></div><div className="grid gap-8 border-t border-[#d8ddea] pt-8 sm:grid-cols-3 lg:absolute lg:left-[860px] lg:top-[150px] lg:h-[540px] lg:w-[748px] lg:border-l lg:border-t-0 lg:pt-0 lg:pl-[99px]">{text.metrics.map(([value, label]) => <div key={label} className="lg:pt-[60px]"><p className="display text-5xl font-medium leading-[60px] text-[#fdda0d]">{value}</p><p className="mt-10 text-lg leading-7 text-[#535a79]">{label}</p></div>)}</div></div></section>
    <section className="bg-[#040406] text-[#d0d9fb] lg:h-[1080px]"><div className="relative mx-auto max-w-[1608px] px-5 py-20 lg:h-[1080px] lg:px-0 lg:py-0"><p className="text-[14.4px] font-medium tracking-[.36px] text-[#fdda0d] lg:absolute lg:left-0 lg:top-[110px]">{text.ecosystem}</p><h2 className="display mt-7 text-3xl font-semibold lg:absolute lg:left-0 lg:top-[160px] lg:mt-0 lg:text-4xl lg:leading-[49.5px]">{text.ecosystemTitle}</h2><div className="mt-12 grid gap-6 md:grid-cols-3 lg:absolute lg:left-0 lg:top-[360px] lg:mt-0 lg:gap-[84px]">{text.capabilities.map(([title, description]) => <article key={title} className="h-[360px] rounded-2xl border border-[#3e445b] bg-[#111520] p-10 lg:h-[560px]"><h3 className="display text-xl font-semibold leading-7 text-[#fdda0d]">{title}</h3><p className="mt-20 text-lg leading-8 text-[#aab4d6]">{description}</p></article>)}</div></div></section>
    <section className="bg-white text-[#1a212d] lg:h-[780px]"><div className="relative mx-auto grid max-w-[1608px] gap-12 px-5 py-20 lg:block lg:h-[780px] lg:px-0 lg:py-0"><div className="lg:absolute lg:left-0 lg:top-[100px] lg:w-[680px]"><p className="text-[14.4px] font-medium tracking-[.36px] text-[#fdda0d]">{text.principlesEyebrow}</p><h2 className="display mt-8 text-3xl font-semibold leading-tight lg:mt-7 lg:text-4xl lg:leading-[49.5px]">{text.principlesTitle}</h2></div><div className="grid gap-10 lg:absolute lg:left-[720px] lg:top-[120px] lg:w-[760px] lg:gap-[74px]">{text.principles.map(([title, description]) => <article key={title}><h3 className="display text-xl font-semibold leading-7">{title}</h3><p className="mt-5 text-lg leading-7 text-[#535a79]">{description}</p></article>)}</div></div></section>
    <CtaBanner locale={locale} /><SiteFooter locale={locale} />
  </main>;
};

export default function AboutPage() { return <About locale="vi" />; }
