import SiteFooter from "@/components/site-footer";
import SiteHeader from "@/components/site-header";
import type { Locale } from "@/lib/i18n";

const inputClass = "h-12 w-full rounded-[6px] border border-[#535a79] bg-[#040406] px-4 text-lg text-[#d0d9fb] outline-none focus:border-[#fdda0d] focus:ring-2 focus:ring-[#fdda0d]/30";
const copy = {
  vi: { label: "LIÊN HỆ", title: <>Hãy bắt đầu bằng<br />bài toán của bạn.</>, body: "Mô tả mục tiêu, quy trình hoặc sản phẩm bạn đang muốn xây dựng. Chúng tôi sẽ cùng bạn xác định bước tiếp theo rõ ràng nhất.", direct: "LIÊN HỆ TRỰC TIẾP", hours: <>Thứ Hai – Thứ Sáu&nbsp; · &nbsp;08:30 – 17:30<br />Việt Nam&nbsp; · &nbsp;Làm việc trực tiếp &amp; từ xa</>, request: "GỬI YÊU CẦU", requestTitle: "Cho chúng tôi biết bạn đang cần gì.", formTitle: "Thông tin liên hệ", fields: ["Họ và tên", "Email", "Công ty", "Chủ đề", "Nội dung"], defaults: ["Nguyễn Văn A", "name@company.com", "Tên doanh nghiệp", "ERP, Web hoặc Computer Vision"], placeholder: "Mô tả ngắn về mục tiêu, hiện trạng và kết quả bạn mong đợi…", submit: "Gửi", consent: "Bằng việc gửi biểu mẫu, bạn đồng ý để KAT Solutions liên hệ về yêu cầu này.", asideTitle: "Một brief tốt có thể bắt đầu rất đơn giản.", aside: ["Bài toán hoặc quy trình hiện tại", "Kết quả bạn muốn đạt được", "Người dùng và phạm vi dự kiến", "Thời gian hoặc mốc triển khai"], reply: "Chúng tôi thường phản hồi trong vòng 1–2 ngày làm việc." },
  en: { label: "CONTACT", title: <>Let&apos;s start with<br />your real challenge.</>, body: "Tell us about the goal, workflow, or product you want to build. Together, we will define the clearest next step.", direct: "CONTACT DIRECTLY", hours: <>Monday – Friday&nbsp; · &nbsp;08:30 – 17:30<br />Vietnam&nbsp; · &nbsp;On-site &amp; remote</>, request: "SEND A REQUEST", requestTitle: "Tell us what you need.", formTitle: "Contact details", fields: ["Full name", "Email", "Company", "Topic", "Message"], defaults: ["Your name", "name@company.com", "Company name", "ERP, Web, or Computer Vision"], placeholder: "Briefly describe your goal, current situation, and the outcome you expect…", submit: "Send", consent: "By submitting this form, you agree that KAT Solutions may contact you about this request.", asideTitle: "A strong brief can start simply.", aside: ["Your current challenge or workflow", "The outcome you want to achieve", "Expected users and scope", "Timeline or delivery milestone"], reply: "We usually respond within 1–2 business days." },
} as const;

export const Contact = ({ locale = "vi" }: { locale?: Locale }) => {
  const text = copy[locale];
  return <main className="bg-white"><SiteHeader active="contact" locale={locale} />
    <section className="bg-[#040406] text-[#d0d9fb] lg:h-[760px]"><div className="relative mx-auto grid min-h-[700px] max-w-[1608px] gap-10 px-5 py-20 lg:block lg:h-[760px] lg:px-0 lg:py-0"><div className="lg:absolute lg:left-0 lg:top-[135px] lg:w-[900px]"><p className="text-[14.4px] font-medium tracking-[.36px] text-[#fdda0d]">{text.label}</p><h1 className="display mt-8 text-4xl font-medium leading-tight lg:mt-7 lg:text-[48px] lg:leading-[60px]">{text.title}</h1><p className="mt-10 max-w-[820px] text-lg leading-8 text-[#aab4d6] lg:mt-[165px] lg:text-xl lg:leading-8">{text.body}</p></div><aside className="rounded-2xl border border-[#3e445b] bg-[#111520] p-10 lg:absolute lg:left-[1048px] lg:top-[120px] lg:h-[500px] lg:w-[560px] lg:p-[47px]"><p className="text-[14.4px] font-medium tracking-[.36px] text-[#fdda0d]">{text.direct}</p><a href="mailto:anh.doanquang98@gmail.com" className="text-link focus-ring display mt-16 block text-xl font-semibold text-[#d0d9fb]">anh.doanquang98@gmail.com</a><p className="mt-16 text-lg leading-7 text-[#aab4d6]">{text.hours}</p></aside></div></section>
    <section className="bg-white text-[#1a212d] lg:h-[1500px]"><div className="relative mx-auto max-w-[1608px] px-5 py-20 lg:h-[1500px] lg:px-0 lg:py-0"><p className="text-[14.4px] font-medium tracking-[.36px] text-[#fdda0d] lg:absolute lg:left-0 lg:top-[75px]">{text.request}</p><h2 className="display mt-6 text-3xl font-semibold lg:absolute lg:left-0 lg:top-[115px] lg:mt-0 lg:text-4xl lg:leading-[49.5px]">{text.requestTitle}</h2><div className="mt-12 grid gap-6 lg:absolute lg:left-0 lg:top-[220px] lg:mt-0 lg:grid-cols-[1120px_420px] lg:gap-[68px]"><form className="rounded-2xl border border-[#d8ddea] p-7 lg:h-[1120px] lg:p-[47px]"><h3 className="display text-xl font-semibold">{text.formTitle}</h3><div className="mt-14 grid gap-10 sm:grid-cols-2"><label className="text-base leading-6 text-[#535a79]">{text.fields[0]}<input className={`${inputClass} mt-[11px]`} defaultValue={text.defaults[0]} /></label><label className="text-base leading-6 text-[#535a79]">{text.fields[1]}<input type="email" className={`${inputClass} mt-[11px]`} defaultValue={text.defaults[1]} /></label><label className="text-base leading-6 text-[#535a79]">{text.fields[2]}<input className={`${inputClass} mt-[11px]`} defaultValue={text.defaults[2]} /></label><label className="text-base leading-6 text-[#535a79]">{text.fields[3]}<input className={`${inputClass} mt-[11px]`} defaultValue={text.defaults[3]} /></label><label className="text-base leading-6 text-[#535a79] sm:col-span-2">{text.fields[4]}<textarea className="mt-[11px] h-[260px] w-full resize-y rounded-lg border border-[#535a79] bg-white p-4 text-lg text-[#1a212d] outline-none focus:border-[#fdda0d] focus:ring-2 focus:ring-[#fdda0d]/30" placeholder={text.placeholder} /></label></div><div className="mt-[60px] flex flex-wrap items-center gap-8"><button type="button" className="focus-ring inline-flex h-12 items-center rounded-[5px] bg-[#fdda0d] px-6 text-lg font-medium text-[#161927]">{text.submit}</button><p className="max-w-[760px] text-base leading-6 text-[#6a708d]">{text.consent}</p></div></form><aside className="rounded-2xl border border-[#d8ddea] p-9 lg:h-[620px] lg:p-[35px]"><h3 className="display text-xl font-semibold leading-7">{text.asideTitle}</h3><ol className="mt-16 grid gap-7 text-lg leading-7 text-[#535a79]">{text.aside.map((item, index) => <li key={item}>0{index + 1}&nbsp;&nbsp; {item}</li>)}</ol><p className="mt-16 text-base leading-6 text-[#fdda0d]">{text.reply}</p></aside></div></div></section><SiteFooter locale={locale} />
  </main>;
};

export default function ContactPage() { return <Contact locale="vi" />; }
